apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-status-probe
  namespace: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-status-probe
  template:
    metadata:
      labels:
        app: http-status-probe
    spec:
      containers:
      - name: http-status-probe
        image: mfonseca21/http-status-probe:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: http-status-probe-service
  namespace: application
spec:
  type: NodePort
  selector:
    app: http-status-probe
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30009 # You can specify a different NodePort if desired